When Exception breakpoint is set and an exception is thrown, pressing Resume works as Step Return.
Pressing "Resume" should resume execution and ignore catched exception, instead debugger stopps until exception isn't catched. It looks like exception was internally rethrown to from each frame to next to the top of stack. We should catch only the "first" throw.